required-players: 2
countdown-seconds: 5
lobby-spawn:
  world: world
  x: 289
  y: 4
  z: 421
  pitch: 0
  yaw: 0
arenas:
  0:
    world: world
    x: 998
    y: 100
    z: 1000
    pitch: 0
    yaw: 0
  1:
    world: world
    x: 100
    y: 100
    z: 100
    pitch: 0
    yaw: 0
